apiVersion: v2
name: aiops
version: 0.1.0
dependencies:
- name: anomaly-detection
  version: 0.1.0
  repository: "file://charts/anomaly-detection"
- name: anomaly-llm
  version: 0.1.0
  repository: "file://charts/anomaly-llm"
- name: redis
  version: 0.1.0
  repository: "file://charts/redis"
