anomaly-detection:
  service:
    port: 8000
  env:
    PROCESS_ANOMALY_URL: http://anomaly-llm.aiops.svc.cluster.local:8001/process-anomaly
    REDIS_HOST: redis.aiops.svc.cluster.local
    REDIS_PORT: 6379
    CHANNEL_NAME: observability-channel
    REDIS_OBS_HOST: redis-service.observability-datamesh.svc.cluster.local
    REDIS_OBS_PORT: 6379

anomaly-llm:
  service:
    port: 8001
  env:
    # CASE_MGT_URL: https://casemanage-dashboard.apps.sno.zagaopensource.com
    CASE_MGT_URL: http://casemgt-backend-api.observability-casemanagement.svc.cluster.local:8000/api/v1/case/
    ACTION_REQ: N
    OPENSHIFT_API_SERVER: https://<openshift api url>:6443
    OPENSHIFT_TOKEN: <token>
    HF_HOME: /mnt/hf_cache
    TRANSFORMERS_CACHE: /mnt/hf_cache/transformers

redis:
  service:
    port: 6379

# postgresql:
#   port: 5432
#   storage: 20Gi
#   user: anomaly
#   password: anomaly123$
#   adminPassword: anomaly123$
#   database: anomalydb
#   # serviceName: postgres-service
#   pvcName: postgres-pvc
#   image: quay.io/osclimate/postgresql-13:1-101
