anomaly-detection:
  service:
    port: 8000
  env:
    REDIS_HOST: redis
    REDIS_PORT: 6379
    PROCESS_ANOMALY_URL: http://anomaly-llm:8001/process-anomaly

anomaly-llm:
  service:
    port: 8001
  env:
    REDIS_HOST: redis
    REDIS_PORT: 6379
    CASE_MGT_URL:
    OPENSHIFT_API_SERVER: https://<openshift api url>:6443
    OPENSHIFT_TOKEN: <token>
    ACTION_REQ: N

redis:
  service:
    port: 6379
