apiVersion: apps/v1
kind: Deployment
metadata:
  name: anomaly-llm-faiss
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: anomaly-llm
  template:
    metadata:
      labels:
        app: anomaly-llm
    spec:
      containers:
        - name: anomaly-llm
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            {{- with .Values.env }}
            {{- range $key, $value := . }}
                        - name: {{ $key }}
                          value: "{{ $value }}"
            {{- end }}
            {{- end }}
          volumeMounts:
            - name: huggingface-cache
              mountPath: /mnt/hf_cache
      volumes:
        - name: huggingface-cache
          emptyDir: {} 