apiVersion: v1
kind: Service
metadata:
  name: anomaly-llm
spec:
  selector:
    app: anomaly-llm
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
