replicaCount: 1
image:
  repository: redis
  tag: 7-alpine
  pullPolicy: IfNotPresent
service:
  port: 6379
persistence:
  enabled: true
  # storageClass: ""
  accessMode: ReadWriteOnce
  size: 20Gi

# auth:
#   enabled: false
#   password: "changeme"
