version: '3.8'

services:
  fastapi-app:
    build: .
    container_name: aiops-llm
    ports:
      - "8001:8001"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8001 --reload
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      # - CASE_MGT_URL=https://casemanage-backend.apps.sno.zagaopensource.com/api/v1/case/
      - CASE_MGT_URL=https://casemanage-backend.apps.zagaopenshift.zagaopensource.com/api/v1/case/
      - OPENSHIFT_API_SERVER=https://<openshift api url>:6443
      - OPENSHIFT_TOKEN=<token>
      - ACTION_REQ=N
    networks:
      - anomaly-network

    # depends_on:
    #   - redis

  # redis:
  #   image: redis:alpine
  #   container_name: redis
  #   ports:
  #     - "6379:6379"
networks:
  anomaly-network:
    external: true

