apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
    app: {{ .Release.Name }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.postgresql.user }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.password }}
  POSTGRESQL_ADMIN_PASSWORD: {{ .Values.postgresql.adminPassword }}
  POSTGRES_DB: {{ .Values.postgresql.database }}
  DATABASE_URL: postgresql://{{ .Values.postgresql.user }}:{{ .Values.postgresql.password }}@postgres-service:5432/{{ .Values.postgresql.database }}
