apiVersion: v1
kind: Service
metadata:
  name: anomaly-detection
spec:
  selector:
    app: anomaly-detection
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}