apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgresql.serviceName }}
spec:
  selector:
    app: {{ .Release.Name }}-postgres
  ports:
    - port: {{ .Values.postgresql.port }}
      targetPort: {{ .Values.postgresql.port }}
  type: ClusterIP
