version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: anomaly-detection
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PROCESS_ANOMALY_URL=http://fastapi-app:8001/process-anomaly
    volumes:
      - ${PWD}:/app
    depends_on:
      - redis
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - anomaly-network

  redis:
    image: redis:7-alpine
    container_name: anomaly-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
        - anomaly-network
  # otel-collector:
  #   image: otel/opentelemetry-collector-contrib:latest
  #   container_name: otel-collector
  #   volumes:
  #     - ./etc/otel/otel-config.yaml:/etc/otelcol-contrib/config.yaml
  #   ports:
  #     - "4317:4317"  # OTLP gRPC
  #     - "4318:4318"  # OTLP HTTP
  #     - "55681:55681" # OpenCensus (optional)
  #   command:
  #     ["--config=/etc/otelcol-contrib/config.yaml"]
  #   networks:
  #     - anomaly-network

volumes:
  redis_data:

networks:
  anomaly-network:
    external: true