replicaCount: 1
image:
  repository: quay.io/zagaos/anomaly-llm-gpt2
  tag: latest
  pullPolicy: Always
service:
  port: 8001
env:
  # REDIS_HOST: redis
  # REDIS_PORT: 6379
  # CASE_MGT_URL: ""
  # OPENSHIFT_API_SERVER: ""
  # OPENSHIFT_TOKEN: ""
